[package]
name = "interception-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evdev = { git="https://github.com/emberian/evdev.git", rev="4c2b319" }
libc = "0.2.144"
nix = "0.26.2"
